config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :job_applications
  get 'home/index'
  resources :job_postings

  get 'my_job_postings', to: 'job_postings#my_job_postings'
  get 'category_jobs', to: 'job_postings#category_jobs'
  get 'job_description', to: 'job_postings#job_description'



  devise_for :employers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  belongs_to :job_posting
  has_one_attached :cv_file
  validates_numericality_of :phone
  validates_presence_of :phone, :first_name, :last_name, :email, :address, :qualification_id, :job_posting_id, allow_blank: false
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  before_action :set_job_application, only: [:show, :edit, :update, :destroy, :download_cv]
  before_action :authenticate_employer!, except: [:new, :create]

  # GET /job_applications
  # GET /job_applications.json
  def index
    @job_applications = JobApplication.where('job_posting_id in (?)', current_employer.job_postings.ids)
  end

  # GET /job_applications/1
  # GET /job_applications/1.json
  def show
  end

  # GET /job_applications/new
  def new
    @job_application = JobApplication.new
    @job_application.job_posting_id = params[:job_posting_id]
    @qualifications = Qualification.all
  end

  # GET /job_applications/1/edit
  def edit
    @qualifications = Qualification.all
  end

  # POST /job_applications
  # POST /job_applications.json
  def create
    @job_application = JobApplication.new(job_application_params)

    respond_to do |format|
      if @job_application.save
        Services::MailSender.send_application_confirmations(@job_application)
        format.html { redirect_to root_path, notice: 'Job application was successfully created.' }
        format.json { render :show, status: :created, location: @job_application }
      else
        format.html { redirect_to new_job_application_path(job_posting_id: job_application_params[:job_posting_id]), alert: @job_application.errors.full_messages }
        format.json { render json: @job_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_applications/1
  # PATCH/PUT /job_applications/1.json
  def update
    respond_to do |format|
      if @job_application.update(job_application_params)
        format.html { redirect_to @job_application, notice: 'Job application was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_application }
      else
        format.html { render :edit }
        format.json { render json: @job_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_applications/1
  # DELETE /job_applications/1.json
  def destroy
    @job_application.destroy
    respond_to do |format|
      format.html { redirect_to job_applications_url, notice: 'Job application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_application
      @job_application = JobApplication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_application_params
      params.require(:job_application).permit(:first_name, :last_name, :birthdate, :email, :phone, :address, :qualification_id, :cv_file, :job_posting_id)
    end
end

app/helpers/job_applications_helper.rb
module JobApplicationsHelper
end

app/views/job_applications/_form.html.erb
<%= form_with(model: job_application, local: true) do |form| %>
  <% if job_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job_application.errors.count, "error") %> prohibited this job_application from being saved:</h2>

      <ul>
        <% job_application.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :birthdate %>
    <%= form.date_select :birthdate, class: 'form-control',start_year: 1920, end_year: 2020, required: true %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.collection_select :qualification_id, @qualifications, :id, :title, {:include_blank => "Choose your qualification"}, {:class=>'form-control input-lg', :id=>'qualification_id', required: true}%>
  </div>

  <div class="form-group">
    <%= form.label 'CV File upload' %>
    <%= form.file_field :cv_file, required: true %>
  </div>

  <%= form.hidden_field :job_posting_id %>

  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/job_applications/edit.html.erb
<h1>Editing Job Application</h1>

<%= render 'form', job_application: @job_application %>

<%= link_to 'Show', @job_application %> |
<%= link_to 'Back', job_applications_path %>

app/views/job_applications/index.html.erb
<div class="container">
  <div class="col-lg-12 col-md-12 col-sm-12">
    <p id="notice"><%= notice %></p>

    <h1>Job Applications</h1>

    <table class="table table-responsive" style="max-width: 100%;">
      <thead>
        <tr>
          <th style="width: 10%">First name</th>
          <th style="width: 10%">Last name</th>
          <th style="width: 10%">Birthdate</th>
          <th style="width: 10%">Email</th>
          <th style="width: 10%">Phone</th>
          <th style="width: 40%">Address</th>
          <th style="width: 10%">Qualification</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @job_applications.each do |job_application| %>
          <tr>
            <td><%= job_application.first_name %></td>
            <td><%= job_application.last_name %></td>
            <td><%= job_application.birthdate %></td>
            <td><%= job_application.email %></td>
            <td><%= job_application.phone %></td>
            <td><%= job_application.address %></td>
            <td><%= Qualification.find(job_application.qualification_id).title %></td>
            <td><%= link_to 'Show', job_application %></td>
            <td><%= link_to 'Edit', edit_job_application_path(job_application) %></td>
            <td><%= link_to 'Destroy', job_application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Job Application', new_job_application_path %>
  </div>
</div>

app/views/job_applications/new.html.erb
<h1>Job Application for <%= @job_application.job_posting.title %></h1>

<%= render 'form', job_application: @job_application %>

<%= link_to 'Back', root_path %>

app/views/job_applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @job_application.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @job_application.last_name %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @job_application.birthdate %>
</p>

<p>
  <strong>Email:</strong>
  <%= @job_application.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @job_application.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @job_application.address %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= Qualification.find(@job_application.qualification_id).title %>
</p>

<p>
  <a href="<%= @job_application.cv_file.attached? ? rails_blob_path(@job_application.cv_file, disposition: 'attachment') : '#' %>" target="_blank" download>Download CV file</a>
</p>

<%= link_to 'Edit', edit_job_application_path(@job_application) %> |
<%= link_to 'Back', job_applications_path %>