config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :job_applications
  get 'home/index'
  resources :job_postings

  get 'my_job_postings', to: 'job_postings#my_job_postings'
  get 'category_jobs', to: 'job_postings#category_jobs'
  get 'job_description', to: 'job_postings#job_description'



  devise_for :employers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :employer
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_employer!, except: [:show]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :owner_id, :business_description, :country, :city)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :owner_id %>
    <%= form.number_field :owner_id %>
  </div>

  <div class="field">
    <%= form.label :business_description %>
    <%= form.text_field :business_description %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Owner</th>
      <th>Business description</th>
      <th>Country</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.owner_id %></td>
        <td><%= company.business_description %></td>
        <td><%= company.country %></td>
        <td><%= company.city %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @company.owner_id %>
</p>

<p>
  <strong>Business description:</strong>
  <%= @company.business_description %>
</p>

<p>
  <strong>Country:</strong>
  <%= @company.country %>
</p>

<p>
  <strong>City:</strong>
  <%= @company.city %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>