config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :job_applications
  get 'home/index'
  resources :job_postings

  get 'my_job_postings', to: 'job_postings#my_job_postings'
  get 'category_jobs', to: 'job_postings#category_jobs'
  get 'job_description', to: 'job_postings#job_description'



  devise_for :employers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

end

app/models/job_posting.rb
class JobPosting < ApplicationRecord
  belongs_to :employer
  belongs_to :category
  belongs_to :qualification
  has_many :job_applications, dependent: :delete_all
  validates_presence_of :title, :description, :email, :expires_in
end

app/controllers/job_postings_controller.rb
class JobPostingsController < ApplicationController
  before_action :set_job_posting, only: [:show, :edit, :update, :destroy, :job_description]
  before_action :authenticate_employer!, except: [:index, :show, :job_description, :category_jobs]


  # GET /job_postings
  # GET /job_postings.json
  def index
    @job_postings = JobPosting.all.paginate(page: params[:page], per_page: 20)
  end

  # GET /job_postings/1
  # GET /job_postings/1.json
  def show
  end

  # GET /job_postings/new
  def new
    @job_posting = JobPosting.new
    @qualifications = Qualification.all
  end

  # GET /job_postings/1/edit
  def edit
    @qualifications = Qualification.all
  end

  # POST /job_postings
  # POST /job_postings.json
  def create
    @job_posting = JobPosting.new(job_posting_params)
    @job_posting.employer_id = current_employer.id

    respond_to do |format|
      if @job_posting.save
        format.html { redirect_to @job_posting, notice: 'Job posting was successfully created.' }
        format.json { render :show, status: :created, location: @job_posting }
      else
        format.html { render :new }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_postings/1
  # PATCH/PUT /job_postings/1.json
  def update
    respond_to do |format|
      if @job_posting.update(job_posting_params)
        format.html { redirect_to @job_posting, notice: 'Job posting was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_posting }
      else
        format.html { render :edit }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_postings/1
  # DELETE /job_postings/1.json
  def destroy
    @job_posting.destroy
    respond_to do |format|
      format.html { redirect_to job_postings_url, notice: 'Job posting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def my_job_postings
    @job_postings = current_employer.job_postings.paginate(page: params[:page], per_page: 10)
  end

  def job_description
    @job_posting
    @expired = @job_posting.expires_in < DateTime.now
  end

  def category_jobs
    category = Category.find(params[:category_id])
    puts "HELLO!"
    render json: category.job_postings
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_posting
      @job_posting = JobPosting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_posting_params
      params.require(:job_posting).permit(:employer_id, :title, :description, :email, :category_id, :expires_in, :qualification_id)
    end
end

app/helpers/job_postings_helper.rb
module JobPostingsHelper
end

app/views/job_postings/_form.html.erb
<%= form_with(model: job_posting, local: true) do |form| %>
  <% if job_posting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job_posting.errors.count, "error") %> prohibited this job_posting from being saved:</h2>

      <ul>
        <% job_posting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.collection_select(:category_id, Category.all.sort_by { |category| category.name }, :id, :name, {:include_blank => "Select category"}, {:class=>'form-control', :required => true})%>
  </div>

  <div class="form-group">
    <%= form.label "Required qualification" %>
    <%= form.collection_select :qualification_id, @qualifications, :id, :title, {:include_blank => "Required qualification"}, {:class=>'form-control input-lg', :id=>'qualification_id'} %>
  </div>

  <div class="form-group">
    <%= form.label :expires_in %>

    <div style="overflow:hidden;">
      <div class="form-group">
        <div class="row">
          <div class="col-md-8">
            <div id="datetimepicker13">
              <%= form.hidden_field(:expires_in,
                  value: form.object.expires_in ? form.object.expires_in.strftime('%I:%M %p') : nil,
                  class: "form-control datetimepicker-input", data: {target:"#datetimepicker13"}) %>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/job_postings/_jobs_available.html.erb
<table class="table">
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Category</th>
    <th>Expires in</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% job_postings.each do |job_posting| %>
    <tr>
      <td><%= link_to job_posting.title, new_job_application_path(job_posting_id: job_posting.id) %></td>
      <td><%= job_posting.description %></td>
      <td><%= job_posting.category.name %></td>
      <td><%= job_posting.expires_in %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/job_postings/edit.html.erb
<h1>Editing Job Posting</h1>

<%= render 'form', job_posting: @job_posting %>

<%= link_to 'Show', @job_posting %> |
<%= link_to 'Back', job_postings_path %>

app/views/job_postings/index.html.erb
<table class="table table-responsive">
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Category</th>
    <th>Expires in</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @job_postings.each_with_index do |job_posting, index| %>
    <tr class="job_post_tr">
      <td style="width: 20%;"><%= link_to job_posting.title, job_description_url(id: job_posting.id) %></td>
      <td style="width: 40%;"><%= job_posting.description %></td>
      <td style="width: 20%;"><%= job_posting.category.name %></td>
      <td style="width: 20%;"><%= job_posting.expires_in %></td>
    </tr>
    <% if job_posting.expires_in < DateTime.now %>
      <%= javascript_tag do %>
        $(".job_post_tr")[<%= index %>].style.background = "red";
        $(".job_post_tr")[<%= index %>].setAttribute("title", "This job posting has expired");
  <% end %>
    <% end %>
  <% end %>
  </tbody>
</table>

<div class="apple_pagination">
  <%= will_paginate @job_postings, :container => false %>
</div>

app/views/job_postings/job_description.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job_posting.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job_posting.description %>
</p>

<p>
  <strong>Email:</strong>
  <%= @job_posting.email %>
</p>

<p>
  <strong>Required qualification:</strong>
  <%= @job_posting.qualification.title %>
</p>

<p>
  <strong>Expires in:</strong>
  <%= @job_posting.expires_in.strftime("%d.%M.%Y") %>
</p>

<% if @expired %>
  This job posting doesn't accept applications anymore |
  <%= link_to 'Back', :back %>
<% else %>
<%= link_to 'Apply', new_job_application_path(job_posting_id: @job_posting.id) %> |
<%= link_to 'Back', :back %>
<% end %>

app/views/job_postings/my_job_postings.html.erb
<p id="notice"><%= notice %></p>

<h1>My Job Postings</h1>

<table class="table table-responsive">
  <thead>
  <tr>
    <th scope="col">Employer</th>
    <th scope="col">Title</th>
    <th scope="col">Description</th>
    <th scope="col">Email</th>
    <th scope="col">Category</th>
    <th scope="col">Expires in</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @job_postings.each do |job_posting| %>
    <tr>
      <td><%= "#{job_posting.employer.first_name} #{job_posting.employer.last_name}" %></td>
      <td><%= job_posting.title %></td>
      <td><%= job_posting.description %></td>
      <td><%= job_posting.email %></td>
      <td><%= job_posting.category.name %></td>
      <td><%= job_posting.expires_in %></td>
      <td><%= link_to 'Show', job_posting %></td>
      <td><%= link_to 'Edit', edit_job_posting_path(job_posting) %></td>
      <td><%= link_to 'Destroy', job_posting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="apple_pagination">
  <%= will_paginate @job_postings, :container => false %>
</div>


<br>

<%= link_to 'New Job Posting', new_job_posting_path, class: 'btn btn-info' %>

<br>
<br>

app/views/job_postings/new.html.erb
<h1>New Job Posting</h1>

<%= render 'form', job_posting: @job_posting %>

<%= link_to 'Back', :back %>

app/views/job_postings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employer:</strong>
  <%= @job_posting.employer_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @job_posting.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job_posting.description %>
</p>

<p>
  <strong>Email:</strong>
  <%= @job_posting.email %>
</p>

<p>
  <strong>Category:</strong>
  <%= @job_posting.category_id %>
</p>

<p>
  <strong>Expires in:</strong>
  <%= @job_posting.expires_in %>
</p>

<%= link_to 'Edit', edit_job_posting_path(@job_posting) %> |
<%= link_to 'Back', job_postings_path %>