config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :job_applications
  get 'home/index'
  resources :job_postings

  get 'my_job_postings', to: 'job_postings#my_job_postings'
  get 'category_jobs', to: 'job_postings#category_jobs'
  get 'job_description', to: 'job_postings#job_description'



  devise_for :employers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

end

app/views/layouts/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-md navbar-light bg-light" id="mainNav">
  <div class="container">
    <%= link_to 'Job Detector', root_path, class: 'navbar-brand js-scroll-trigger' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">

          <li class="nav-item">
            <%= link_to 'Job Postings', job_postings_path, class: 'nav-link js-scroll-trigger' %>
          </li>

        <% if current_employer %>
          <li class="nav-item">
            <%= link_to 'Applications', job_applications_url, class: 'nav-link js-scroll-trigger' %>
          </li>

          <li class="nav-item">
            <%= link_to 'My job postings', my_job_postings_path, class: 'nav-link js-scroll-trigger' %>
          </li>

          <li class="nav-item">
            <%= link_to 'Log out', destroy_employer_session_path, method: "delete" , class: 'nav-link js-scroll-trigger' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log in', new_employer_session_path, class: 'nav-link js-scroll-trigger' %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Job Detector</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container" style="min-height: 88.3vh;">
      <% if notice %>
        <p class="alert alert-success" style="margin-top: 70px;"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger" style="margin-top: 70px;"><%= alert %></p>
      <% end %>

      <div class="common col-lg-12 col-md-12 col-sm-12">
      <%= yield %>
      </div>
    </div>
  </body>

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Luka Povreslo <%= Time.now.year %></p>
    </div>
    <!-- /.container -->
  </footer>
</html>